name: SimpleMessages
main: RevivalPMMP\SimpleMessages\SimpleMessages
version: 1.0.0
api: [2.1.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2]

authors: ["RevivalPMMP"]
description: A Super Simple Messaging Plugin for Pocketmine
website: https://github.com/RevivalPMMP/SimpleMessages
